# Generated by Django 3.2.9 on 2021-11-29 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ra', models.CharField(max_length=8)),
                ('cpf', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fiap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.CharField(choices=[('1', 'Iniciada'), ('2', 'Em Análise'), ('3', 'Finalizada')], default='1', max_length=20)),
                ('dataInicio', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 8, 26, 59, 777000))),
                ('dataFinal', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 8, 26, 59, 777000), null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Importancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Satisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_turma', models.CharField(default='', max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('periodo', models.CharField(choices=[('1', 'Manhã'), ('2', 'Tarde'), ('3', 'Noite')], default='1', max_length=15)),
                ('dataInicio', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 8, 26, 59, 774980))),
            ],
        ),
        migrations.CreateModel(
            name='uploadCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(null=True, upload_to='imports/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('identificador', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=50)),
                ('nivelAcesso', models.CharField(choices=[('1', 'Aluno'), ('2', 'Professor'), ('3', 'Analista'), ('4', 'Coordenador')], default='1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advverbal', models.BooleanField(blank=True, default=False, null=True)),
                ('advescrita', models.BooleanField(blank=True, default=False, null=True)),
                ('afastamento', models.BooleanField(blank=True, default=False, null=True)),
                ('cancelmatricula', models.BooleanField(blank=True, default=False, null=True)),
                ('fiap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.fiap')),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 8, 26, 59, 779997))),
                ('fiap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fiap')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulasprevistas', models.IntegerField()),
                ('ausencias', models.IntegerField()),
                ('fiap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.fiap')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aluno')),
                ('importancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.importancia')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pergunta')),
                ('satisfacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.satisfacao')),
            ],
        ),
        migrations.AddField(
            model_name='fiap',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.turma'),
        ),
        migrations.AddField(
            model_name='fiap',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.TextField()),
                ('coordenador', models.TextField()),
                ('social', models.TextField()),
                ('aluno', models.TextField()),
                ('responsavel', models.TextField()),
                ('fiap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.fiap')),
            ],
        ),
        migrations.CreateModel(
            name='Aproveitamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notamedia', models.IntegerField()),
                ('notaaluno', models.IntegerField()),
                ('notarec', models.IntegerField(blank=True, null=True)),
                ('fiap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.fiap')),
                ('materia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Aprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencao', models.BooleanField(blank=True, default=False, null=True)),
                ('compreensao', models.BooleanField(blank=True, default=False, null=True)),
                ('comprometimento', models.BooleanField(blank=True, default=False, null=True)),
                ('relacionamento', models.BooleanField(blank=True, default=False, null=True)),
                ('Outros', models.CharField(blank=True, max_length=100, null=True)),
                ('fiap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.fiap')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.turma'),
        ),
    ]
