# Generated by Django 3.2.8 on 2021-11-30 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211129_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='turma',
        ),
        migrations.AddField(
            model_name='fiap',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.materia'),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 10, 25, 2, 321367), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 10, 25, 2, 321367)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 10, 25, 2, 323365)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 10, 25, 2, 319366)),
        ),
    ]
