# Generated by Django 3.2.9 on 2021-12-20 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211220_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 10, 19, 2, 384213), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 10, 19, 2, 384213)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 10, 19, 2, 390197)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 10, 19, 2, 382220)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
