# Generated by Django 3.2.9 on 2021-12-20 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211220_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 10, 32, 16, 50819), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 10, 32, 16, 49822)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 10, 32, 16, 53811)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 20, 10, 32, 16, 48825), null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='periodo',
            field=models.CharField(blank=True, choices=[('1', 'Manhã'), ('2', 'Tarde'), ('3', 'Noite')], default='1', max_length=15, null=True),
        ),
    ]
