# Generated by Django 4.0.1 on 2022-01-21 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211220_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='dataFinal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 21, 8, 48, 16, 793062), null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Em andamento'), ('2', 'Finalizado')], default='1', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 8, 48, 16, 794074), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 8, 48, 16, 794074)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 8, 48, 16, 797072)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 21, 8, 48, 16, 793062), null=True),
        ),
    ]
