# Generated by Django 3.2.9 on 2022-01-24 11:02

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211220_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[48, 48], upload_to='avatar_image/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 8, 2, 21, 279623), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 8, 2, 21, 279623)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 8, 2, 21, 282615)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 24, 8, 2, 21, 277628), null=True),
        ),
    ]
