# Generated by Django 4.0 on 2022-01-29 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_fiap_datafinal_alter_fiap_datainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 3, 6, 588368), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 3, 6, 588368)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 3, 6, 591370)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataFinal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 29, 17, 3, 6, 587368), null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 29, 17, 3, 6, 587368), null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='periodo',
            field=models.CharField(choices=[('1', 'Manhã'), ('2', 'Tarde'), ('3', 'Noite')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('1', 'Em andamento'), ('2', 'Finalizado')], default='1', max_length=15),
        ),
    ]
