# Generated by Django 4.0 on 2022-02-02 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_assinatura_dataaluno_assinatura_datacoordenador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinatura',
            old_name='dataAluno',
            new_name='alunoData',
        ),
        migrations.RenameField(
            model_name='assinatura',
            old_name='dataCoordenador',
            new_name='coordenadorData',
        ),
        migrations.RenameField(
            model_name='assinatura',
            old_name='dataDocente',
            new_name='docenteData',
        ),
        migrations.RenameField(
            model_name='assinatura',
            old_name='dataResponsavel',
            new_name='responsavelData',
        ),
        migrations.RenameField(
            model_name='assinatura',
            old_name='dataSocial',
            new_name='socialData',
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 18, 48, 48, 431120, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 18, 48, 48, 431120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 18, 48, 48, 433120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataFinal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 2, 18, 48, 48, 429119, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 2, 18, 48, 48, 429119, tzinfo=utc), null=True),
        ),
    ]
